swagger: '2.0'
info:
  title: Onboarding API (FORMS+JSON)
  version: ''
  description: |-
    Onboarding API for BigCo, Inc.

    This is a fORMS+JSON API sketch
host: onboarding.example.org
basePath: /
schemes:
  - http
paths:
  /:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          examples:
            application/forms+json:
              home:
                - title: Show Home Page
                  forms:
                    - name: list
                      href: /list
                      method: get
                      properties: []
                  items: []
      summary: Show Home Page
      description: ''
      tags: []
      parameters: []
      produces:
        - application/forms+json
  /list:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          examples:
            application/forms+json:
              home:
                - title: Show Onboarding Record List
                  forms:
                    - name: list
                      href: /list
                    - name: create
                      href: /list
                      method: post
                      properties:
                        - name: id
                          value: 1q12w3e4r5t
                  items:
                    - id: 1q2w3e4r5t
                      href: /1q2w3e4r5t
                      status: pending
                      other-proprrties: ...
      summary: Show Onboarding Record List
      description: ''
      tags: []
      parameters: []
      produces:
        - application/forms+json
    post:
      responses:
        '201':
          description: Created
          headers: {}
          examples:
            application/forms+json:
              home:
                - title: 'ITEM:1q2w3e4r5t Created'
                  forms:
                    - name: list
                      href: /list
                  items:
                    - id: 1q2w3e4r5t
                      href: /1q2w3e4r5t
                      other-properties: ...
      summary: Create Onboarding Record
      description: ''
      tags: []
      parameters: []
      produces:
        - application/forms+json
  /1q2w3e4r5t:
    get:
      responses:
        '200':
          description: OK
          headers: {}
          examples:
            application/forms+json:
              home:
                - title: 'ITEM:1q2w3e4r5t'
                  forms:
                    - name: list
                      href: /list
                    - name: collectCompanyInfo
                      href: /1q2w3e4r5t
                      method: patch
                      properties:
                        - name: id
                          value: 1q2w3e4r5t
                        - name: href
                          value: /1q2w3e4r5t
                        - name: status
                          value: pending
                        - name: company-properties
                          value: ...
                    - name: collectAccountInfo
                      href: /1q2w3e4r5t
                      method: patch
                      properties:
                        - name: id
                          value: 1q2w3e4r5t
                        - name: href
                          value: /1q2w3e4r5t
                        - name: status
                          value: pending
                        - name: account-properties
                          value: ...
                    - name: collectionActivityInfo
                      href: /1q2w3e4r5t
                      method: patch
                      properties:
                        - name: id
                          value: 1q2w3e4r5t
                        - name: href
                          value: /1q2w3e4r5t
                        - name: status
                          value: pending
                        - name: activity-properties
                          value: ...
                    - name: approveRecord
                      href: /approve
                      method: patch
                      properties:
                        - name: id
                          value: 1q2w3e4r5t
                        - name: status
                          value: active
                    - name: rejectRecord
                      href: /reject
                      method: post
                      properties:
                        - name: id
                          value: 1q2w3e4r5t
                        - name: status
                          value: closed
                  items:
                    - id: 1q2w3e4r5t
                      href: /1q2w3e4r5t
                      status: pending
                      other-properties: ...
      summary: Show Onboarding Record
      description: ''
      tags: []
      parameters: []
      produces:
        - application/forms+json
    patch:
      responses:
        '302':
          description: Found
          headers: {}
          examples: {}
      summary: Update Onboarding Record
      description: ''
      tags: []
      parameters: []
  /approve:
    patch:
      responses:
        '200':
          description: OK
          headers: {}
          examples:
            application/forms+json:
              home:
                - title: 'ITEM:1q2w3e4r5t Approved'
                  forms:
                    - name: list
                      href: /list
                  items: []
      summary: Approve Onboarding Record
      description: ''
      tags: []
      parameters: []
      produces:
        - application/forms+json
  /reject:
    patch:
      responses:
        '200':
          description: OK
          headers: {}
          examples:
            application/forms+json:
              home:
                - title: 'ITEM:1q2w3e4r5t Rejected'
                  forms:
                    - name: list
                      href: /list
                  items: []
      summary: Reject Onboarding Record
      description: ''
      tags: []
      parameters: []
      produces:
        - application/forms+json
definitions:
  Home: {}
  Onboarding List: {}
  Onboarding Record: {}
  Approve Onboarding: {}
  Reject Onboarding: {}
